//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Common.Loclizable {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class NotificationMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NotificationMessage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ERP.Common.Loclizable.NotificationMessage", typeof(NotificationMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Approved {
            get {
                return ResourceManager.GetString("Approved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endorsed {0} for connection with reference {1}..
        /// </summary>
        public static string EndorsedForConnection {
            get {
                return ResourceManager.GetString("EndorsedForConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endorsed  {0} with reference {1} for your inspection..
        /// </summary>
        public static string EndorseForHWInspection {
            get {
                return ResourceManager.GetString("EndorseForHWInspection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} house wiring inspection for {1} with reference {2}.
        /// </summary>
        public static string ProcessHouseWiringInspection {
            get {
                return ResourceManager.GetString("ProcessHouseWiringInspection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recommend {0} with reference {1} for your approval..
        /// </summary>
        public static string RecommendForApproval {
            get {
                return ResourceManager.GetString("RecommendForApproval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inspection for  {0} with reference {1} has been re-assigned..
        /// </summary>
        public static string RemoveHWInspection {
            get {
                return ResourceManager.GetString("RemoveHWInspection", resourceCulture);
            }
        }
    }
}
